services:
  d0:
    container_name: dev-0
    hostname: d0
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      PASSWORD: wil3jX5a08Ck
    ports:
      - 6900:22
      - 6910:8080
    volumes:
      - ./d0:/workspaces
  d1:
    container_name: dev-1
    hostname: d1
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      PASSWORD: h6Ff6d6T0a63
    ports:
      - 6901:22
      - 6911:8080
    volumes:
      - ./d1:/workspaces

networks:
  default:
    name: dev
