services:
  dev:
    container_name: dev-container
    hostname: dev
    image: ghcr.io/thaddeuskkr/dev-container:main
    restart: unless-stopped
    environment:
      PASSWORD: YOUR_PASSWORD # This is set for the users "ubuntu" and "root"
      KEYS: | # A list of public keys to copy to ~/.ssh/authorized_keys
        ssh-rsa abc
    ports:
      - "2222:22"
    volumes:
      - ~/.gnupg:/volumes/.gnupg:ro
      - ~/.gitconfig:/volumes/.gitconfig:ro
      - ./workspaces:/workspaces
      - home:/home/ubuntu

volumes:
  home:

networks:
  default:
    name: dev
