services:
  dev:
    container_name: dev-container
    hostname: dev # The hostname is the name of the tunnel (by default)
    image: ghcr.io/thaddeuskkr/dev-container:main
    restart: unless-stopped
    environment:
      PASSWORD: YOUR_PASSWORD # This is set for the users "ubuntu" and "root"
    volumes:
      - ~/.gnupg:/volumes/.gnupg:ro
      - ~/.gitconfig:/volumes/.gitconfig:ro
      - ./workspaces:/workspaces
      - ./data/:/data
      # - /var/run/docker.sock:/var/run/docker.sock # Optional - if you want to use Docker within the container
      - home:/home/ubuntu

volumes:
  home: