#!/bin/bash
echo "root:$PASSWORD" | chpasswd
echo "ubuntu:$PASSWORD" | chpasswd
mkdir -p /home/ubuntu/.gnupg
cp -R /volumes/.gnupg/* /home/ubuntu/.gnupg
cp /volumes/.gitconfig /home/ubuntu
chown -R ubuntu:ubuntu /home/ubuntu/.gnupg
chown -R ubuntu:ubuntu /home/ubuntu/.gitconfig
chown -R ubuntu:ubuntu /workspaces
chown -R ubuntu:ubuntu /data
sudo -u ubuntu bash -c 'code tunnel --accept-server-license-terms --server-data-dir /data/server --extensions-dir /data/extensions --cli-data-dir /data/cli'
