#!/bin/bash
chown -R ubuntu:ubuntu /workspaces
echo "root:$PASSWORD" | chpasswd
echo "ubuntu:$PASSWORD" | chpasswd
mkdir -p /home/ubuntu/.ssh
echo "$KEYS\n" >> /home/ubuntu/.ssh/authorized_keys
chown -R ubuntu:ubuntu /home/ubuntu/.ssh
/usr/sbin/sshd -D
