#!/bin/bash
chown -R ubuntu:ubuntu /workspaces
echo "root:$PASSWORD" | chpasswd
echo "ubuntu:$PASSWORD" | chpasswd
mkdir -p /home/ubuntu/.ssh
mkdir -p /home/ubuntu/.gnupg
echo "$KEYS\n" >> /home/ubuntu/.ssh/authorized_keys
cp -R /volumes/.gnupg/* /home/ubuntu/.gnupg
chown -R ubuntu:ubuntu /home/ubuntu/.ssh
chown -R ubuntu:ubuntu /home/ubuntu/.gnupg
/usr/sbin/sshd -D
